version: "2"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - ineffassign
    - unused
    - gocritic
    - bodyclose
    - noctx
    - unparam
    - misspell
    - prealloc
    - errname
    - errorlint
    - nilnil
    - wastedassign
    - maintidx
    - godox
    - goprintffuncname

formatters:
  enable:
    - gofmt
    - goimports