ALTER TABLE games
ADD COLUMN IF NOT EXISTS initial_time_ms BIGINT NOT NULL DEFAULT 600000;

ALTER TABLE games
ADD COLUMN IF NOT EXISTS increment_ms BIGINT NOT NULL DEFAULT 0;

ALTER TABLE games
ADD COLUMN IF NOT EXISTS white_time_ms BIGINT NOT NULL DEFAULT 600000;

ALTER TABLE games
ADD COLUMN IF NOT EXISTS black_time_ms BIGINT NOT NULL DEFAULT 600000;

ALTER TABLE games
ADD COLUMN IF NOT EXISTS current_turn VARCHAR(10) NOT NULL DEFAULT 'w';

ALTER TABLE games
ADD COLUMN IF NOT EXISTS turn_started_at TIMESTAMPTZ;
