ALTER TABLE users ADD COLUMN IF NOT EXISTS rating_deviation DOUBLE PRECISION NOT NULL DEFAULT 350;
ALTER TABLE users ADD COLUMN IF NOT EXISTS rating_volatility DOUBLE PRECISION NOT NULL DEFAULT 0.06;
ALTER TABLE users ADD COLUMN IF NOT EXISTS games_played INTEGER NOT NULL DEFAULT 0;
