ALTER TABLE games
ADD COLUMN IF NOT EXISTS rating_applied BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE player_ratings
ADD COLUMN IF NOT EXISTS wins INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS losses INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS draws INTEGER NOT NULL DEFAULT 0;
