name: Deploy to AWS EC2 with Docker

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build -t caisaara-backend:latest .
          docker save -o caisaara-backend.tar caisaara-backend:latest

      - name: Copy Docker image to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "caisaara-backend.tar"
          target: "/home/${{ secrets.EC2_USERNAME }}/app"

      - name: Load and Run Docker Container on EC2
        uses: appleboy/ssh-action@master
        env:
          ENV_FILE_CONTENT: ${{ secrets.ENV_FILE_CONTENT }}
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          envs: ENV_FILE_CONTENT
          script: |
            # Ensure the app directory exists
            mkdir -p /home/${{ secrets.EC2_USERNAME }}/app
            cd /home/${{ secrets.EC2_USERNAME }}/app
            
            # Write the GitHub secret to the .env file securely
            echo "$ENV_FILE_CONTENT" > .env
            
            # Load the new Docker image
            docker load -i caisaara-backend.tar
            
            # Stop and remove the existing container if it exists
            docker stop caisaara-backend || true
            docker rm caisaara-backend || true
            
            # Run the new container
            # This assumes you have manually placed your .env file in the /home/${{ secrets.EC2_USERNAME }}/app directory
            docker run -d --name caisaara-backend --env-file .env -p 8080:8080 caisaara-backend:latest
            
            # Clean up the tar file to save space
            rm caisaara-backend.tar
